### ISSUE TITLE
Question about the random encoder

### ISSUE THREAD

**Issue by GilgameshD** [paruby/Wasserstein-Auto-Encoders#1]
Thanks for your great work!

I have one question about the implementation of the random encoder. What is the difference between the random encoder and the reparameterization trick in VAE?

**Comment by paruby** [comment]
Hi GilgameshD, hope it's not too late to answer your question.

The implementation of random encoders is the same as is used in VAEs. The reparameterization trick refers to sampling from the encoding distribution and feeding this sample into the generator/decoder to allow backpropagation of gradients through the sampling, even though the encoder defines a distribution over the latent space. 

This is implemented in e.g. https://github.com/paruby/Wasserstein-Auto-Encoders/blob/master/models.py#L637-L639

**Comment by paruby** [comment]
Let me know if that doesn't answer your question!

**Comment by GilgameshD** [comment]
Thanks! Your answer dispelled my doubts
